### ISSUE TITLE
Move under CMB-S4

### ISSUE THREAD

**Issue by zonca** [CMB-S4/serverless-data-portal-cmb-s4#1]
What if we move the repo under the CMB-S4 github organization https://github.com/CMB-S4?
I am admin so it should be straightforward.
I think it would make the preview url look more official.

We could rename the repository serverless-data-portal-cmb-s4?

**Comment by rpwagner** [comment]
Fine by me! Whatever works best for the project.

**Comment by rpwagner** [comment]
Let me know if I need to rename this repo to make it easier move, or do anything else.

**Comment by zonca** [comment]
thanks @rpwagner, yes, better if you rename this repository and then request transfer to `CMB-S4`. I should then be able to accept the incoming transfer on the other end. Then I'll add you as external collaborator and admin on the repository.

**Comment by rpwagner** [comment]
I think you would need to give me [permission to create public repos](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) to transfer this.

> To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.

Do you want to just create an empty repo and I'll push the current history to it? Then I'll archive this repo and start a new issue about the initial manifests and pages.

**Comment by zonca** [comment]
what if you put me admin on this repo? not sure if that works

**Comment by zonca** [comment]
idea!
you transfer to me and I transfer into the org 8)

**Comment by rpwagner** [comment]
There we go! That should work. I sent the transfer request.

**Comment by zonca** [comment]
very good it worked, @rpwagner is outside collaborator of the org and admin of this repo.
