### ISSUE TITLE
Update Globus groups

### ISSUE THREAD

**Issue by zonca** [CMB-S4/serverless-data-portal-cmb-s4#11]
@jdborrill last time I merged the CMB-S4 membership to the data portal globus group was 1 year ago or so.
And only 53 people had a Globus account at the time out of 340.

Should I run another import? If so I can ask Jeff about a new dump of the membership DB.

We currently have no need for the Data-Management-only group, so let's wait before populating it.

## Globus SDK script

https://www.zonca.dev/posts/2021-09-24-globus-groups-python-sdk

**Comment by zonca** [comment]
I am updating the membership in the group with the latest membership list by @jdborrill.
I have about 360 members.

I first added users using the "Login Address" and the `CMB-Se4` group went from 53 to 74 members.

**Comment by zonca** [comment]
I reran using "Email Address", membership is now at 77 people.

**Comment by jdborrill** [comment]
I don't understand why it isn't 362 members.

Julian

**Comment by zonca** [comment]
only adds people that have a Globus account with that email address

**Comment by zonca** [comment]
only adds people that have a Globus account with that email address already

**Comment by zonca** [comment]
if we run this nightly via #14, people create a Globus account and then are added to the globus group the next day

**Comment by jdborrill** [comment]
I thought Globus wasn't a requirement to access the data, just an add-on.

J

**Comment by rpwagner** [comment]
You don't have to use Globus Transfer, but permissions are managed via Globus accounts and Globus Groups. So a user needs to login into Globus at least once to create an account and join the Group. Then they can use HTTPS to download the data. 

For public data, then there's no need for a Globus account.

**Comment by jdborrill** [comment]
Hmmm ... is that the only mechanism to manage permissions?

If so, we will need to capture people's globus accounts (which we currently
don't do) which may be different from their google identity or their
preferred email address.

Julian

**Comment by zonca** [comment]
You can have multiple email addresses associated to the same Globus account, so I think we could do the other way around and ask people to add their Google Identity or their preferred email address to their globus account.

**Comment by rpwagner** [comment]
Yes, this is the only way to manager permissions on Globus Guest Collections. So this applies to the current setup hosted here and UCSD and what you'll have in the future at NERSC. As Andrea wrote, multiple identities can be associated with a Globus account, so usually a collaborator will have linked their institutional identity (UCSD, LBL, etc.) with Globus.

There's several ways to do this, some of which can be automated with the Globus CLI or via their REST API. I'd be glad to join the discussion to figure out what's smoothest for your current onboarding process and IAM services.

**Comment by jdborrill** [comment]
A discussion sounds good - we should include Jeff Anderson who runs the
CMB-S4 LDAP too.

Julian

**Comment by zonca** [comment]
@jdborrill @jdanderson3 @rpwagner as per our discussion today,
I have created 3 subgroups of CMB-S4:
![image](https://user-images.githubusercontent.com/383090/226687451-ae83100f-9f67-4a16-9c03-fffcd0f6efbe.png)

Currently all users are in the CMB-S4 group and the subgroups are empty, once the script will have populated all the groups, we can change permissions on the portal.

**Comment by zonca** [comment]
@jdborrill and @jdanderson3 are admins of the group

**Comment by zonca** [comment]
this should now be handled automatically, see #14
