### ISSUE TITLE
Publish all Planck NPIPE products

### ISSUE THREAD

**Issue by zonca** [CMB-S4/serverless-data-portal-cmb-s4#12]
@keskitalo do you have a reference suitable for the version of the Planck NPIPE release? Also what does 6v20 mean? is it a version number?

You can directly make a pull request to https://github.com/CMB-S4/serverless-data-portal-cmb-s4/blob/main/npipe6v20.md to add a bit of description.

Also, we should publish all the folders on the portal, right?
![image](https://user-images.githubusercontent.com/383090/226078141-ac4f7deb-df95-4b07-bed2-866726300625.png)

@jdborrill is it ok if we make all NPIPE products public?

**Comment by keskitalo** [comment]
6v20 is the internal version number. It just stuck after the production was done.  On the PLA everything is labeled R4.0 (for PR4).

The best reference is the paper, https://www.aanda.org/articles/aa/abs/2020/11/aa38073-20/aa38073-20.html and of course there is the explanatory supplement we prepared for the PLA: https://wiki.cosmos.esa.int/planck-legacy-archive/index.php/NPIPE_Introduction

**Comment by zonca** [comment]
@rpwagner ok, we can rename the `NPIPE` folder to `public/planck/planck_pr4/` and publish all the subfolders and generate all the markdown pages. Also the sidebar and all the titles should call the release Planck PR4 (Planck Public Release 4).
If you can take care of that, then I will add more documentation to the pages.

**Comment by rpwagner** [comment]
@zonca I'm starting on this now. I'll let you know when things are moved and renamed so you can work on the content.

**Comment by rpwagner** [comment]
Checkout PR #15 

The datasets have been moved to [`/public/planck/planck_pr4/`](https://app.globus.org/file-manager?origin_id=38f01147-f09e-483d-a552-3866669a846d&origin_path=%2Fpublic%2Fplanck%2Fplanck_pr4%2F).

**Comment by zonca** [comment]
thanks @rpwagner! merged it in.

**Comment by zonca** [comment]
@keskitalo I noticed that the files in the data portal have different naming and different organization compared to the ones available via https://portal.nersc.gov/cfs/cmb/planck2020/frequency_maps/, is there a reason for that?

**Comment by zonca** [comment]
@rpwagner I added a Globus icon on the PR4 pages to make it more prominent, would it be possible to do the same with DC0? if it is easy to rerun your scripts or to write a small ad-hoc script.
If it is too time consuming nevermind.

**Comment by rpwagner** [comment]
Done. Take a look at #17 and see if that's what you expected.

**Comment by keskitalo** [comment]
> @keskitalo I noticed that the files in the data portal have different naming and different organization compared to the ones available via https://portal.nersc.gov/cfs/cmb/planck2020/frequency_maps/, is there a reason for that?

Those are the maps delivered to PLA. The file structure and naming conventions match earlier releases but are a little cumbersome and not well suited for the NPIPE A/B subsets.

**Comment by zonca** [comment]
ok, I added all the docs
