### ISSUE TITLE
Update all DC-0 data

### ISSUE THREAD

**Issue by zonca** [CMB-S4/serverless-data-portal-cmb-s4#18]
@rpwagner we have an updated release for DC-0

![Screenshot 2023-03-31 09 08 43](https://user-images.githubusercontent.com/383090/229174071-d10f6fdb-b1ae-47c4-aa7b-38d8cbbe1224.png)

the filenames have changed a little bit, for example:

    dc0_chlat_t32.21_280_map02_c1111.fits

there is an extra 1 in the `c1111`

I am copying it into the `inbox` via Globus

Running in:

```
exclude *c0001*
exclude *c0010*
exclude *c0100*
exclude *c1000*
exclude *mat02*
```

**Comment by rpwagner** [comment]
OK. When the transfer completes I'll move it to the data releases area and updated the manifests and references on the pages.

**Comment by zonca** [comment]
@rpwagner would you have any updates on this? Thanks!

**Comment by rpwagner** [comment]
@zonca sorry, nothing yet. I'll be able to work on it starting tomorrow afternoon.

**Comment by rpwagner** [comment]
I'm generating the manifests now. Should be able to have a pull request with the updated pages done tomorrow.
