### ISSUE TITLE
TOAST NPIPE data release

### ISSUE THREAD

**Issue by zonca** [CMB-S4/serverless-data-portal-cmb-s4#2]
I started the transfer for the first dataset to the Globus endpoint of UCSD.
It is about 300 GB.

We have the more important data products (FITS files in HEALPix format) in the root folder, then 4 subfolders with other data products.

It would be nice to have a markdown document rendered for each folder with the description of data products in that folder.

Initially I thought we could have that markdown be in the data source, so that people can maintain it without accessing the data portal, however, it is just a useless complication. Better have those markdown files here in the repository, anyone can do a PR to improve them.

**Comment by rpwagner** [comment]
I know what you mean about where to maintain the descriptions and metadata. I would suggest a Python script or notebook to create the basic description as JSON. The JSON can live with the data and be input to create the initial Markdown.

**Comment by zonca** [comment]
Initially we can have for each folder an html page, with a markdown file rendered at the top (We can have it empty initially, then I can manually insert a description)
then link to the subfolders,
then list of all files with their size, so it would be nice if we can query the Globus API to get the file list and the file sizes and store that in the repository.

**Comment by rpwagner** [comment]
I can get [the code together](https://github.com/rpwagner/serverless-data/blob/main/serverless-data/serverless_data/dataset.py) to build basic JSON files and Markdown with manifests (file names, size, etc.) for datasets or folders. It'll be quick to iterate on what the content should be.Plus, we can get most of from Globus. 

I'd also like to include checksums, or at store them somewhere. But that can be a one-time process and we'll store the manifest file separately.

```
$ globus ls -l 38f01147-f09e-483d-a552-3866669a846d:inbox/lowres/
Permissions | User              | Group                 | Size        | Last Modified             | File Type | Filename                            
----------- | ----------------- | --------------------- | ----------- | ------------------------- | --------- | ------------------------------------
0660        | researchit-globus | researchit-uss-admins | 10871635968 | 2022-10-08 00:40:19+00:00 | file      | npipe6v20_ncm_ns0032_030_bin.dat    
0660        | researchit-globus | researchit-uss-admins | 10871635968 | 2022-10-08 00:41:26+00:00 | file      | npipe6v20_ncm_ns0032_030_inv_bin.dat
0660        | researchit-globus | researchit-uss-admins | 10871635968 | 2022-10-08 00:41:27+00:00 | file      | npipe6v20_ncm_ns0032_044_bin.dat    
0660        | researchit-globus | researchit-uss-admins | 10871635968 | 2022-10-08 00:41:20+00:00 | file      | npipe6v20_ncm_ns0032_044_inv_bin.dat
0660        | researchit-globus | researchit-uss-admins | 10871635968 | 2022-10-08 00:55:18+00:00 | file      | npipe6v20_ncm_ns0032_070_bin.dat    
0660        | researchit-globus | researchit-uss-admins | 10871635968 | 2022-10-08 01:00:06+00:00 | file      | npipe6v20_ncm_ns0032_070_inv_bin.dat
0660        | researchit-globus | researchit-uss-admins | 10871635968 | 2022-10-08 01:01:11+00:00 | file      | npipe6v20_ncm_ns0032_100_bin.dat    
0660        | researchit-globus | researchit-uss-admins | 10871635968 | 2022-10-08 01:01:12+00:00 | file      | npipe6v20_ncm_ns0032_100_inv_bin.dat
0660        | researchit-globus | researchit-uss-admins | 10871635968 | 2022-10-08 01:06:12+00:00 | file      | npipe6v20_ncm_ns0032_143_bin.dat    
0660        | researchit-globus | researchit-uss-admins | 10871635968 | 2022-10-08 01:15:06+00:00 | file      | npipe6v20_ncm_ns0032_143_inv_bin.dat
0660        | researchit-globus | researchit-uss-admins | 10871635968 | 2022-10-08 01:19:27+00:00 | file      | npipe6v20_ncm_ns0032_217_bin.dat    
0660        | researchit-globus | researchit-uss-admins | 10871635968 | 2022-10-08 01:19:23+00:00 | file      | npipe6v20_ncm_ns0032_217_inv_bin.dat
0660        | researchit-globus | researchit-uss-admins | 10871635968 | 2022-10-08 01:21:25+00:00 | file      | npipe6v20_ncm_ns0032_353_bin.dat    
0660        | researchit-globus | researchit-uss-admins | 10871635968 | 2022-10-08 01:29:24+00:00 | file      | npipe6v20_ncm_ns0032_353_inv_bin.dat```

**Comment by zonca** [comment]
yes, very good! Then once I see how this works I can help out.

**Comment by zonca** [comment]
@rpwagner any update on this? please let me know if I can do anything to help!

**Comment by rpwagner** [comment]
@zonca thanks for pinging me. Give a couple of days and I'll come back with either questions or some a basic example for discussion.

**Comment by rpwagner** [comment]
@zonca I've done the PR for the basic site: #3 

I also made you an administrator of those two Globus Groups I created. They’re documented on the landing page. This could probably be put on a separate page. It’s also important to communicate and get feedback on how data access is managed. Maybe we can get a few more datasets up as examples and then when you do have a chance to present we can make some slides about it.

The only step that requires processing the files is creating the manifest with the checksums. That could be coupled to other processes that extract other relevant metadata from the files. I’m not very familiar with FITS so I didn’t grab anything from the info cards. But, that could be extracted and put onto the dataset pages.

I’ll go ahead and get the other dataset folders up with minimal pages. You can let me know if they should be broken down into smaller datasets. It would also help to have at least one dataset for each data access pattern: public, self-registration, moderated.

**Comment by rpwagner** [comment]
Also, if there are any images from the project, the data release, or datasets that can hosted publicly, I can create the examples for embedding them. For now, we can only link to images that aren't public. (Longish story about Globus's HTTPS implementation.)
