### ISSUE TITLE
input sky to DC-0

### ISSUE THREAD

**Issue by zonca** [CMB-S4/serverless-data-portal-cmb-s4#21]
@rpwagner @jdborrill we have a new dataset of input sky simulated with PySM that are going to be used in DC-0.

I am transferring the files to /inbox/dc0_sky/

the docs of the release are at https://github.com/CMB-S4/s4mapbasedsims/blob/main/202305_dc0/README.md

however, we only want to host on the portal the "combined" maps.

**Comment by jdborrill** [comment]
Hi Andrea,

I thought the SO skies were there too (and the LiteBIRD and SPO to follow).
I think it makes sense to store these as the PanEx V1 skies for those 4
instruments.

Julian

**Comment by zonca** [comment]
Ok, so let's do a data release "PanEx V1 skies", and put CMB-S4 dataset
below it.
Then I'll transfer Simons Observatory as well

Il dom 30 lug 2023, 21:02 Julian Borrill ***@***.***> ha
scritto:

**Comment by jdborrill** [comment]
Perfect! And then we can add LiteBIRD and SPO as they become available.
Maybe have placeholder stubs there so people can see they're coming.

And this release should be public, whereas DC0 will be private (at least
initially).

J

**Comment by rpwagner** [comment]
I'll take a look at this early next week and draft a new data public data release.

**Comment by zonca** [comment]
@rpwagner a reminder of this

**Comment by rpwagner** [comment]
@zonca thanks, I've been out on vacation and let this slip more than intended.

**Comment by zonca** [comment]
@rpwagner it seems like I cannot check a folder size on Globus, so it is easier if you do it on the receiving machine.
can you please write here the total size of `/inbox/dc0_sky`?

**Comment by rpwagner** [comment]
> @rpwagner it seems like I cannot check a folder size on Globus, so it is easier if you do it on the receiving machine.
> can you please write here the total size of `/inbox/dc0_sky`?

`148 GB`

**Comment by zonca** [comment]
files for S4 are published in #26, needs more documentation

**Comment by zonca** [comment]
good enough for now, we will improve when we add other releases
