### ISSUE TITLE
Publish DC-0 output maps to the portal

### ISSUE THREAD

**Issue by zonca** [CMB-S4/serverless-data-portal-cmb-s4#22]
we should put the outputs of DC-0 on the portal with some urgency because we want to use it as method of delivery to the working groups as part of the Data Challenge process.

We have simulations of Chile LAT and South Pole SAT available, but they are too large, we need to decide what subset we want to publish to the portal.

CHLAT maps size, total **6.4T**

```
104G    split01
208G    split02
415G    split04
829G    split08
1.7T    split16
3.3T    split32
``` 

The SAT maps are very small, so no problem with those.

@smsimon do you know what the working groups are expecting, can we just do `split01` and `split02`? We currently have 1 TB storage total at UCSD.

**Comment by zonca** [comment]
Naming schema is explained here:
https://docs.google.com/document/d/1VIQYsGMza9rOn3E0GY1hDpzLN4hcR7Fwm7tpXGUxSlY/edit?usp=sharing

For each split and frequency we have:

* all the individual components
* the full map `c1111`
* the depth map (`map03`)
* the white noise covariance matrix

```
zonca@login33 025 $ pwd -P
/global/cfs/cdirs/cmbs4/dc/dc0/mission/chlat/split01/025
zonca@login33 025 $ ls -lah
total 18G
drwxr-x--- 2 keskital cmbs4 4.0K Aug 24 16:48 .
drwxr-x--- 8 keskital cmbs4 4.0K Aug 24 18:13 ..
-rw-r----- 1 keskital cmbs4 2.3G Aug 24 16:46 dc0_chlat_t01.01_025_map02_c0001.fits
-rw-r----- 1 keskital cmbs4 2.3G Aug 24 16:47 dc0_chlat_t01.01_025_map02_c0010.fits
-rw-r----- 1 keskital cmbs4 2.3G Aug 24 16:47 dc0_chlat_t01.01_025_map02_c0100.fits
-rw-r----- 1 keskital cmbs4 2.3G Aug 24 16:47 dc0_chlat_t01.01_025_map02_c1000.fits
-rw-r----- 1 keskital cmbs4 2.3G Aug 24 16:48 dc0_chlat_t01.01_025_map02_c1111.fits
-rw-r----- 1 keskital cmbs4 1.6G Aug 24 16:45 dc0_chlat_t01.01_025_map03.fits
-rw-r----- 1 keskital cmbs4 4.6G Aug 24 16:46 dc0_chlat_t01.01_025_mat02.fits
```

**Comment by smsimon** [comment]
We should put what splits we can on the portal so your plan of putting up split01 and split02 sounds reasonable. I can contact the AWGs that need more splits to let them know where to find them.

**Comment by smsimon** [comment]
Note: The description portion on the DC0 page also needs some minor edits:

1. "DC-0 is the first execution of a Data Challenge run, it has been completed only for Large Aperture Telescopes located in Chile (CHLAT), the rest of the channels are still being worked on." to 

"DC-0 is the first execution of a Data Challenge run, it has been completed for the Large Aperture Telescopes located in Chile (CHLAT) and the South Pole Small-Aperture Telescopes (SATs), the SPLAT is still being worked on."

2. "The full documentation of the release will be published publicly, for now it is being worked on in the Github repository [CMB-S4/DataChallenge0](https://github.com/CMB-S4/DataChallenge0), only accessible to Github accounts members of the CMB-S4 Github organization." 

This link points to the old instrument design. If we wanted to have something ready ASAP we could point to the "Technical Design to Measurement Requirements" section of the PBDR https://github.com/CMB-S4/PreliminaryBaselineDesignReport

**Comment by zonca** [comment]
@smsimon please feel free to edit the file directly and make a pull request to this repository with the improvements:
https://github.com/CMB-S4/serverless-data-portal-cmb-s4/blob/main/dc0.md

**Comment by zonca** [comment]
@rpwagner ok, the new DC-0 files finished transferring to UCSD

**Comment by zonca** [comment]
@smsimon new DC-0 release on the portal #25 
https://data.cmb-s4.org/dc0.html

**Comment by smsimon** [comment]
Thanks, sent to the AWGs.
