### ISSUE TITLE
Data releases on the portal and disk space

### ISSUE THREAD

**Issue by zonca** [CMB-S4/serverless-data-portal-cmb-s4#23]
### DC-0 outputs

* CHLAT split01/split02 312 GB
* SPSAT split01/split02 7GB

### Panexp V1

* CMB-S4 (input sky to DC-0), just combined maps, 148 GB (already on the portal)
* SPT ~100 GB (not ready yet)
* LiteBIRD small (not ready yet)

### Planck PR4 (already on the portal)

- [Link](https://data.cmb-s4.org/planck_pr4-fullsky.html)	Full sky maps	27	10.4 GiB
- [Link](https://data.cmb-s4.org/planck_pr4-half_ring.html)	Half-ring maps	90	77.3 GiB
- [Link](https://data.cmb-s4.org/planck_pr4-lowres.html)	Low resolution maps	63	155.4 GiB
- [Link](https://data.cmb-s4.org/planck_pr4-quickpol.html)	Effective Beams	1049	312.7 MiB
- [Link](https://data.cmb-s4.org/planck_pr4-single.html)	Single channel maps	171	63.7 GiB

If we remove the obsolete DC-0 release which is now on the portal, we should fit in 1 TB. @rpwagner ?

**Comment by rpwagner** [comment]
Let me check the current allocations from our collections. I may be able to increase CMB-S4 allocation for the next 6 months.

**Comment by zonca** [comment]
@rpwagner can you please delete the old DC-0 files from the portal so we have space for the new files in #22 ? Thanks!

**Comment by zonca** [comment]
sorry @rpwagner we are a bit in a hurry with DC-0 delivery, can you clear up some space so I can start the transfer?

**Comment by rpwagner** [comment]
Go ahead and start the transfer, there's no hard quota enforcement. I'm working out how much we can increase the allocation.

**Comment by rpwagner** [comment]
@zonca I'm going to set a quota to 5TB. That should allow all of the DC0 datasets except split32, plus others.

**Comment by zonca** [comment]
@rpwagner excellent thanks, for now let's just put on the portal the 2 splits I have already transferred, later we will decide what to do with the others. Thanks!

**Comment by zonca** [comment]
@rpwagner we are in a hurry to publish the DC-0 to the data portal to deliver to people doing the analysis.
Is it possible to have them published in the next couple of days?

**Comment by rpwagner** [comment]
@zonca, yes, I can have the PR finished tomorrow. Just so I'm clear, all of the current DC-0 datasets (CHLAT spilts 01 thru 32) are being replaced with the newer CHLAT and SPLAT splits 01 and 02, correct?

**Comment by zonca** [comment]
correct

**Comment by rpwagner** [comment]
Got it. Later on, well should have a discussion later about dataset versions and obsolesce. There are plenty of best practices and guidelines we can draw from, so it's mostly a matter of documenting whatever process we choose. This can be a topic for one of the DC0 or DM & Sims calls.

**Comment by rpwagner** [comment]
@zonca I need to finish this up tomorrow (Friday). I'm replicating the data over to the data release folder and then I'll generate the updated catalog pages.

**Comment by zonca** [comment]
see #28, we plan to only host public datasets at UCSD

**Comment by zonca** [comment]
we have our data hosted on the NERSC filesystem with no duplication, so we are not worried about disk space as much.
