### ISSUE TITLE
Additional DC-0 files

### ISSUE THREAD

**Issue by zonca** [CMB-S4/serverless-data-portal-cmb-s4#27]
We currently only have DC-0 CHLAT and SPSAT for full mission.
@keskitalo do we have other maps we should publish?
I also plan to add the half-mission maps for all telescopes.

**Comment by keskitalo** [comment]
The SPLAT maps are in the same location as CHLAT and SPSAT. However, we are currently reviewing the SPLAT filter stack and may decide to rerun SPLAT. Will know for sure early next week.

The half mission maps are in the same directories as the full mission maps.

**Comment by zonca** [comment]
@keskitalo are the new maps ready yet?

**Comment by keskitalo** [comment]
Not yet

**Comment by zonca** [comment]
maps are available, I moved them to:

    /global/cfs/cdirs/cmbs4/gsharing/datareleases/dc0/mission

and symlinked from the previous location:

```
[cmbs4@dtn01 mission]$ pwd 
/global/cfs/cdirs/cmbs4/dc/dc0/mission
[cmbs4@dtn01 mission]$ ls -l
total 5
lrwxrwxrwx 1 cmbs4 cmbs4   63 Nov 29 22:51 chlat -> /global/cfs/cdirs/cmbs4/gsharing/datareleases/dc0/mission/chlat
lrwxrwxrwx 1 cmbs4 cmbs4   63 Nov 29 22:51 splat -> /global/cfs/cdirs/cmbs4/gsharing/datareleases/dc0/mission/splat
drwxr-x--- 8 cmbs4 cmbs4 4096 Sep 19 19:50 splat_OLD
lrwxrwxrwx 1 cmbs4 cmbs4   63 Nov 29 22:51 spsat -> /global/cfs/cdirs/cmbs4/gsharing/datareleases/dc0/mission/spsat
drwxr-x--- 8 cmbs4 cmbs4 4096 Aug 24 10:55 spsat_OLD
```

Currently the portal expects the old files, so it might be broken.
Next I'll update the portal to publish all the files in this release.

**Comment by rpwagner** [comment]
@zonca FYI, [Globus doesn't follow symlinks](https://docs.globus.org/faq/transfer-sharing/#how_does_globus_handle_symlinks). Not sure if that applies in this case, and you can also you hard links at NERSC if I recall.

**Comment by zonca** [comment]
Yes, that is why I moved data under the globus folder and symlinked from the original location to the globus folder

**Comment by zonca** [comment]
ok @keskitalo @jdborrill I have now published all entire DC0 release, so we have all the splits and we have SPLAT.
We should probably think of a better organization of the sidebar.
