### ISSUE TITLE
Public data at NERSC

### ISSUE THREAD

**Issue by zonca** [CMB-S4/serverless-data-portal-cmb-s4#31]
As part of #28, I requested to have anonymous HTTPS access for our public datasets and now it is active, therefore we can move the public Planck PR4 data from UCSD to NERSC.

The release is on the portal at https://data.cmb-s4.org/planck_pr4.html, in total it is about 300 GB.

My first proposal would be to just duplicate the data under:

    /global/cfs/cdirs/cmbs4/gsharing

I think we have those files under the CMB account instead of the S4 account, so using symlinks or hardlinks will probably not work due to permissions. @jdborrill do you agree?

**Comment by jdborrill** [comment]
For CFS space-management purposes, all public data (currently Planck and
PanEx/PySM, but should be extended to include eg. ACT DR6) should be in the
cmb CFS space; all private CMB-S4 data should be in the cmbs4 CFS space.
When CMB-S4 data go public, they should be moved to the cmb space.

We don't have the space to duplicate things, but we can leave a symlink
from the cmbs4 to the cmb CFS space when data are moved.

We need to review and clean-up whatever is currently in the cmb space; what
is left should all be made available through the portal so we don't have to
give out accounts just to copy data elsewhere.

Julian

**Comment by zonca** [comment]
ok, so the only way to achieve this would be to enable another Globus guest collection that points to the folder (currently doesn't exist):

     `/global/cfs/cdirs/cmb/gsharing`

and then have the data portal point to the cmb-s4 `gsharing` for the S4 data and to the `cmb` `gsharing` folder for the public data.
It is a bit more complicated but manageable.

**Comment by zonca** [comment]
@jdborrill do agree with creating a separate Globus collection for the CMB CFS? see details above

**Comment by zonca** [comment]
@jdborrill I think the 2 other panexp v1 skies, i.e. SO and Litebird, could me moved from cmbs4xlitebird and from the simons observatory space into the CMB CFS.
Then I'll setup another endpoint in the CMB space so that we can also serve them from S4 data portal.
Ok for me to move them and then put symlinks at their previous location?

**Comment by jdborrill** [comment]
Sounds good to me, yes.

Julian

**Comment by zonca** [comment]
requested Globus Collection for the `cmb` project space.
Moved data under:

    /global/cfs/cdirs/cmb/gsharing/

Put symlinks in previous location in SO and in CMBS4xlite project spaces. Data are set to be accessible by everyone at NERSC, so there should not be permission issues.

**Comment by zonca** [comment]
ok,
I created the globus collection, `53b2a147-ae9d-4bbf-9d18-3b46d133d4bb`, @tskisner is administrator as well.
It allows anonymous read for everyone, no need for a globus account. This way people can quickly download a map just via HTTPS from the data portal.

**Comment by zonca** [comment]
@jdborrill I have published simons observatory https://data.cmb-s4.org/
I'm now working on Litebird

**Comment by zonca** [comment]
@jdborrill, ok, also litebird is published
