### ISSUE TITLE
Storage of CMB-S4 data releases at NERSC for the data portal

### ISSUE THREAD

**Issue by zonca** [CMB-S4/serverless-data-portal-cmb-s4#32]
The root of the data portal is:

    /global/cfs/cdirs/cmbs4/gsharing

the globus sharing is not able to follow symlinks.

Therefore in order to avoid duplicating the data, I think we have 2 options:

1. Use symlinks: move the data, for example `/global/cfs/cdirs/cmbs4/dc/dc0/mission/chlat` to `/global/cfs/cdirs/cmbs4/gsharing/datareleases/dc0/chlat` and then turn the original folder in a symlink, this has the downside that we cannot choose what files we share inside the folder
2. Use hardlinks: we could create hardlinks on `/global/cfs/cdirs/cmbs4/gsharing` that point to the data under `/global/cfs/cdirs/cmbs4/dc/dc0/`, hard links are file by file, this is easy to do recursively with `cp -al src dest`, and allows us to write more complicated scripts to only share a subset of data. However it requires more maintenance, if we replace or add files in the original folder, we need to remember to propagate the changes to the `gsharing` folder

@keskitalo @jdborrill @tskisner do you have suggestions, considerations?

**Comment by jdborrill** [comment]
See my reply to the other issue.

Julian

**Comment by zonca** [comment]
@jdborrill we still need to decide between softlinks and hardlinks

**Comment by zonca** [comment]
I decided to go with softlinks.
