### ISSUE TITLE
Add id to JSON LD

### ISSUE THREAD

**Issue by zonca** [CMB-S4/serverless-data-portal-cmb-s4#39]
at top of markdown pages, put an id inside the `seo` tag, used by Jekyll extension to create valid JSON LD for example for Google Dataset search

https://raw.githubusercontent.com/CMB-S4/serverless-data-portal-cmb-s4/main/dc0-spsat-split08-025.md

**Comment by zonca** [comment]
@rpwagner I am looking at:

https://jekyll.github.io/jekyll-seo-tag/usage/
https://jekyll.github.io/jekyll-seo-tag/advanced-usage/

what field do you think is the JSON-LD id? `name`?

**Comment by zonca** [comment]
@rpwagner unfortunately jekyll seo tag only supports `@id` for objects of type `WebPage` and it is set automatically to the url of the page:

https://github.com/jekyll/jekyll-seo-tag/blob/f449b1af64cbaf9080e7a3c677090cfe6e8f0021/lib/jekyll-seo-tag/json_ld_drop.rb#L79-L85

I tested on https://data.cmb-s4.org/dc0-spsat-split08-025.html

**Comment by zonca** [comment]
here is how it currently is for all other files:

```json
{
"@context": "http://schema.org",
"@type": "Dataset",
"name": "CMB-S4 DC0 SPSAT Split08 085GHz",
"creator": {
"@type": "Organization",
"name": "CMB-S4 Collaboration"
},
"description": "CMB-S4 DC0 SPSAT Split08 085GHz",
"temporalCoverage": "2023-12-07"
}
```

**Comment by zonca** [comment]
name is different from `@id`

**Comment by rpwagner** [comment]
We can move away from the SEO tag, but we'll need to create a template. [Here's a basic guide](https://bioschemas.org/tutorials/howto/howto_add_github) if we want to do that. This will also let us add custom metadata.

**Comment by zonca** [comment]
@rpwagner it was already implemented!

I just improved it in [219c2ea](https://github.com/CMB-S4/serverless-data-portal-cmb-s4/commit/219c2ea6f34b444e74b5c776c5fde21752ec235f) and f047942617abc0df91250df3e9f98a9692d7b1ae

```json
{
"@context": "http://schema.org",
"@type": "Dataset",
"@id": "cmb-s4-dc0-spsat-split08-025ghz",
"name": "CMB-S4 DC0 SPSAT Split08 025GHz",
"creator": {
"@type": "Organization",
"name": "CMB-S4 Collaboration"
},
"description": "CMB-S4 DC0 SPSAT Split08 025GHz",
"temporalCoverage": "2023-12-07"
}
```

I create it automatically from "description" using `slugify`, so it is now added automatically to all pages!

**Comment by zonca** [comment]
actually, better to use `title`, even if they are currently equal
