### ISSUE TITLE
Installed and customized the Jekyll Docs Theme

### ISSUE THREAD

**Issue by zonca** [CMB-S4/serverless-data-portal-cmb-s4#6]
Using this theme: https://github.com/tomjoht/documentation-theme-jekyll

I like the sidebar which can give quick access to all different releases. Now it is a bit sad with only 1 release but it will grow.

Only problem is that it seems like it expects no hierarchy of folders, so I had to flatten the structure of the pages.
Annoying but I think it is doable. @rpwagner?

**Comment by rpwagner** [comment]
I like the layout and I think this is fine for now. But, it may become unwieldy to have all the files in the top directory as more more releases are created, especially if releases or datasets begin to have different versions. Until then, let's go with it.
